# Módulo 2. Adquisición de datos - Archivos y BBDDs

******

******

## 1. Lectura de archivos (en un mundo ideal)

Pandas ofrece gran cantidad de opciones cuando se trata de leer y exportar datos.

In [2]:
import pandas as pd

Vamos a examinar un conjunto de datos que contiene información sobre los crimenes en USA desde 2020 hasta la actualidad. Podeís encontrar el dataset [aquí](https://drive.google.com/file/d/1rF77Fq3jEcvqh_xX4V3z4t3ZeK0TDmRR/view?usp=sharing)

In [7]:
csv_data = pd.read_csv('../Data/Data_Aquisition/Crime_USA.csv')
csv_data.head(2)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545

Echemos un vistazo a nuestro DataFrame:

In [8]:
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690454 entries, 0 to 690453
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           690454 non-null  int64
 1   Date Rptd       690454 non-null  object
 2   DATE OCC        690454 non-null  object
 3   TIME OCC        690454 non-null  int64
 4   AREA            690454 non-null  int64
 5   AREA NAME       690454 non-null  object
 6   Rpt Dist No     690454 non-null  int64
 7   Part 1-2        690454 non-null  int64
 8   Crm Cd          690454 non-null  int64
 9   Crm Cd Desc     690454 non-null  object
 10  Mocodes         595482 non-null  object
 11  Vict Age        690454 non-null  int64
 12  Vict Sex        599971 non-null  object
 13  Vict Descent    599965 non-null  object
 14  Premis Cd       690446 non-null  float64
 15  Premis Desc     690092 non-null  object
 16  Weapon Used Cd  239966 non-null  float64
 17  Weapon Desc     239966 non-null  object
 18  Status          690454 non-null  object
 19  Status Desc     690454 non-null  object
 20  Crm Cd 1        690445 non-null  float64
 21  Crm Cd 2        51536 non-null   float64
 22  Crm Cd 3        1733 non-null    float64
 23  Crm Cd 4        52 non-null      float64
 24  LOCATION        690454 non-null  object
 25  Cross Street    112242 non-null  object
 26  LAT             690454 non-null  float64
 27  LON             690454 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 147.5+ MB

Fijaros que estoy usando un archivo csv. Sin embargo, si el mismo archivo estuviera en otros formatos también sería muy fácil leer estos:

- Archivo MS Excel: `excel_data = pd.read_excel('Crime_USA.xlsx')` -> En un mundo perfecto...

- Archivo JSON: `json_data = pd.read_json('Crime_USA.json')`

- Archivo Parquet:`parquet_data = pd.read_parquet('Crime_USA.parquet')`

- Archivo Feather:`feather_data = pd.read_feather('Crime_USA.feather')`

De hecho, haciendo una prueba:

Peso:

<img src="https://drive.google.com/uc?id=1q2s4RdUzN77g33coANgycPLjJT3D0lSZ" width="40%">

Segundos en cargar:

- CSV

<img src="https://drive.google.com/uc?id=1KT57fV8AqrJmifeBcxy2x3XJPe30_DGU" width="30%">

- MS Excel

<img src="https://drive.google.com/uc?id=1T6c7zrCXELhXVcgboenHw7DoiI8A8tLO" width="30%">

- JSON

<img src="https://drive.google.com/uc?id=15t80xGFZwsnWzUxtWzqFGVScmVxWspBm" width="30%">

- Parquet

<img src="https://drive.google.com/uc?id=1kUJ4S3eo1dfMlOpDITbGyQ2kKzhLjNej" width="40%">

- Feather

<img src="https://drive.google.com/uc?id=1WLkz3_x7XM8EHo6naCCdjvBHswbJFHUy" width="40%">

Resumiendo...

In [10]:
import plotly.express as px

df = pd.DataFrame(dict(
    archivo = ["CSV", "XLSX", "JSON", "PARQUET", "FEATHER"],
    tiempo_carga_seg = [3.36, 225.6, 21.11, 1.89, 0.99],
    tamano_mb = [176.4, 78.4, 382.4, 29.7, 84.7]))

fig = px.bar(df, x = 'archivo', y = 'tiempo_carga_seg')
fig.update_layout(title_text='Tiempo en cargar', title_x=0.5)
fig.show()

fig = px.bar(df, x = 'archivo', y = 'tamano_mb')
fig.update_layout(title_text='Tamaño', title_x=0.5)
fig.show()

**¿Y que hay de los demás archivos?** Los demás tipos de archivos que hemos visto anteriormente, a exceptción de XML, no están creados para almacenar grandes conjuntos de datos. Por lo que su comparación sería injusta. Como anecdota, convertí el conjunto de datos a un archivo HTML y pesaba más de 500 MB. Por otro lado, no hemos visto XML aún, debido a que es muy parecido a HTML, por lo que lo veremos más adelante.

**¿Y que ocurre con una plantilla MS Excel? ¿Y con los datos de un PDF?** -> Lo veremos en manipulación de datos

******

******

## 2. Lectura de Bases de Datos

Algunas de las librerías más comunes para leer bases de datos en Python incluyen Pandas, SQLAlchemy y PyMySQL. Pandas es una librería popular para la manipulación de datos, y puede leer datos de bases de datos SQL. SQLAlchemy es una librería de mapeo de objetos relacionales (ORM) que permite trabajar con bases de datos SQL de manera más fácil. PyMySQL es una librería específica de Python para trabajar con bases de datos MySQL.

Para leer datos de una base de datos en Python, es necesario conectarse a la base de datos utilizando un controlador de base de datos, que es una librería específica para el tipo de base de datos que se está utilizando. Una vez conectado a la base de datos, se puede usar SQL (Structured Query Language) para enviar consultas a la base de datos y recuperar los datos deseados.

Python tiene librerías que pueden ejecutar consultas SQL en la base de datos y devolver los resultados en un objeto DataFrame de Pandas, lo que facilita el análisis de los datos recuperados. Además, Python tiene librerías que pueden conectarse a bases de datos no SQL, como MongoDB y Cassandra, y realizar operaciones de lectura y escritura en estas bases de datos.

In [11]:
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in C:\Users\Adrian\anaconda3\envs\DS_training\Lib\site-packages (2.0.54)
Requirement already satisfied: greenlet>=1 in C:\Users\Adrian\anaconda3\envs\DS_training\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Adrian\anaconda3\envs\DS_training\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: pymysql in C:\Users\Adrian\anaconda3\envs\DS_training\Lib\site-packages (1.2.3)

Para que SQLAlchemy se conecte a nuestra base de datos, debemos definir lo siguiente:

- dialect+driver: ¿Nuestra base de datos es MySQL, PostgreSQL, etc? ¿A qué DBAPI debe conectarse nuestro motor?
- username:password: ¿Qué credenciales necesitamos para conectarnos a nuestra base de datos?
- host:port: ¿Dónde está nuestra base de datos?
- database: ¿Cómo se llama nuestra base de datos?

In [ ]:
import sqlalchemy as sa

dialect = "mysql"
driver = "pymysql"
username = "usuario1"
password = "C0d35p4ce."
host = "database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com"
port = "3306"
database = "classicmodels"

#* Habria que conectar con mi base de datos de aws
connection_string = f"{dialect}+{driver}://{username}:{password}@{host}:{port}/{database}"
engine = sa.create_engine(connection_string)

Fijaros que sencillo es trasladar mis datos a un DataFrame:

In [13]:
text = """
SELECT *
FROM products
"""

conn = engine.connect()
query = sa.text(text)

query_df = pd.read_sql(query, con=conn)
query_df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

También podemos utilizar la siguiente sentencia para poder consultar todos los datos de una tabla:

In [14]:
conn = engine.connect()

table_df = pd.read_sql_table("products", con=conn)
table_df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Aunque no es necesario utilizar la librería Pandas:

In [15]:
conn = engine.connect()

result = conn.execute(sa.text("""SELECT * FROM products""")).fetchall()
result

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

También podemos investigar sobre nuestro esquema:

In [16]:
from sqlalchemy import inspect
inspector = inspect(engine)

for table_name in inspector.get_table_names():
    print("\n")
    for column in inspector.get_columns(table_name):
        print(f"Table: {table_name} | Column: {column['name']}")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
inspector = inspect(engine)
inspector.get_columns('products')

[{'name': 'productCode',
  'type': VARCHAR(length=15),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'productName',
  'type': VARCHAR(length=70),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'productLine',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'productScale',
  'type': VARCHAR(length=10),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'productVendor',
  'type': VARCHAR(length=50),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'productDescription',
  'type': TEXT(),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'quantityInStock',
  'type': SMALLINT(),
  'default': None,
  'comment': None,
  'nullable': False,
  'autoincrement': False},
 {'name': 'buyPrice',
  'type': DECIMAL(precision=10, scale=2),
  'default': None,
  'comment': None,
  'nullable': False},
 {'name': 'MSRP',
  'type': DECIMAL(precision=10, scale=2),
  'default': None,
  'comment': None,
  'nullable': False}]

### 2.1. Otros aspectos a considerar con SQLAlchemy

Podeís borrar, actualizar o insertar registros/tablas sin ningún problema con SQLAlchemy, sin embargo esta base de datos no tiene los permisos necesarios y este módulo trata solo sobre problemas de adquisición (lectura), no de volcado de datos (escritura).

# Ejercicios

1. En un nuevo notebook, llama a la BBDD que se uso en módulos anteriores llamada `classicmodels`. Tras esto, realiza una consulta SQL para consultar cuanto stock hay según la linea de producto.
2. Realiza lo mismo, pero con las funciones de Pandas, es decir, extrae la tabla completa y realiza la agrupación con las funciones de Pandas.

In [1]:
import sqlalchemy as sa

dialect = "mysql"
driver = "pymysql"
username = "admin"
password = "Boxerlisa12"
host = "database-code-space.cjcco20qexih.eu-north-1.rds.amazonaws.com"
port = "3306"
database = "classicmodels"

#* Habria que conectar con mi base de datos de aws
connection_string = f"{dialect}+{driver}://{username}:{password}@{host}:{port}/{database}"
engine = sa.create_engine(connection_string)

In [7]:
text = """
SELECT productLine, sum(quantityInStock) as quantityInStock
FROM products
GROUP BY productLine
"""

conn = engine.connect()
query = sa.text(text)

query_df = pd.read_sql(query, con=conn)
query_df

        productLine  quantityInStock
0      Classic Cars         219183.0
1       Motorcycles          69401.0
2            Planes          62287.0
3             Ships          26833.0
4            Trains          16696.0
5  Trucks and Buses          35851.0
6      Vintage Cars         124880.0

In [6]:
text = """
SELECT *
FROM products
"""

conn = engine.connect()
query = sa.text(text)

query_df = pd.read_sql(query, con=conn)
query_df

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00
...,...,...,...,...,...,...,...,...,...
105,S700_3505,The Titanic,Ships,1:700,Carousel DieCast Legends,"Completed model measures 19 1/2 inches long, 9...",1956,51.09,100.17
106,S700_3962,The Queen Mary,Ships,1:700,Welly Diecast Productions,Exact replica. Wood and Metal. Many extras inc...,5088,53.63,99.31
107,S700_4002,American Airlines: MD-11S,Planes,1:700,Second Gear Diecast,Polished finish. Exact replia with official lo...,8820,36.27,74.03
108,S72_1253,Boeing X-32A JSF,Planes,1:72,Motor City Art Classics,"10"" Wingspan with retractable landing gears.Co...",4857,32.77,49.66
109,S72_3212,Pont Yacht,Ships,1:72,Unimax Art Galleries,Measures 38 inches Long x 33 3/4 inches High. ...,414,33.30,54.60

In [8]:
query_df = query_df[["productLine", "quantityInStock"]]
query_df=query_df.groupby("productLine")["quantityInStock"].sum().reset_index()
query_df

        productLine  quantityInStock
0      Classic Cars         219183.0
1       Motorcycles          69401.0
2            Planes          62287.0
3             Ships          26833.0
4            Trains          16696.0
5  Trucks and Buses          35851.0
6      Vintage Cars         124880.0